{% set version = "1.2.2" %}
{% set major,minor,patch = version.split('.') %}

package:
  name: libwebp-base
  version: {{ version }}

source:
  url: http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-{{ version }}.tar.gz
  sha256: 7656532f837af5f4cec3ff6bafe552c044dc39bf453587bd5b77450802f4aee6
  patches: patches/windows_declspec.patch  # [win]

build:
  number: 1
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libwebp
    - {{ pin_compatible('libwebp-base') }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - make  # [not win]
    - ninja # [win]
    - cmake # [win]
    - m2-patch # [win]
  run_constrained:
    # 1.1 is when libwebp-base was split from libwebp
    - libwebp {{ version }}

test:
  commands:
    - test -f $PREFIX/lib/libwebp.a               # [not win]
    - test -f $PREFIX/lib/libwebp{{ SHLIB_EXT }}  # [not win]
    - test -f $PREFIX/include/webp/decode.h       # [not win]
    - test -f $PREFIX/include/webp/encode.h       # [not win]
    - test -f $PREFIX/include/webp/types.h        # [not win]
    - if not exist %CONDA_PREFIX%\\Library\\lib\\libwebp.lib exit 1            # [win]
    - if not exist %CONDA_PREFIX%\\Library\\lib\\libwebpdemux.lib exit 1       # [win]
    - if not exist %CONDA_PREFIX%\\Library\\lib\\libwebpdecoder.lib exit 1     # [win]
    - if not exist %CONDA_PREFIX%\\Library\\bin\\libwebp.dll exit 1            # [win]
    - if not exist %CONDA_PREFIX%\\Library\\bin\\libwebpdemux.dll exit 1       # [win]
    - if not exist %CONDA_PREFIX%\\Library\\bin\\libwebpdecoder.dll exit 1     # [win]
    - if not exist %CONDA_PREFIX%\\Library\\bin\\cwebp.exe exit 1              # [win]
    - if not exist %CONDA_PREFIX%\\Library\\bin\\dwebp.exe exit 1              # [win]
    - if not exist %CONDA_PREFIX%\\Library\\include\\webp\\decode.h exit 1     # [win]
    - if not exist %CONDA_PREFIX%\\Library\\include\\webp\\encode.h exit 1     # [win]
    - if not exist %CONDA_PREFIX%\\Library\\include\\webp\\types.h exit 1      # [win]

about:
  home: https://developers.google.com/speed/webp
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: WebP image library
  description: |
    WebP is a method of lossy and lossless compression that can be used on a
    large variety of photographic, translucent and graphical images found on the
    web. The degree of lossy compression is adjustable so a user can choose the
    trade-off between file size and image quality.
    libwebp-base provides the headers and shared libraries. For cwebp and dwep,
    binaries install libwebp.
  doc_url: https://developers.google.com/speed/webp/docs/using
  dev_url: https://chromium.googlesource.com/webm/libwebp

extra:
  recipe-maintainers:
    - carterbox
    - dschreij
    - ocefpaf
